spring:
  application:
    name: consumer
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: demo-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer

app:
  topic:
    name: demo-topic